### ISSUE TITLE
Help Wanted - Troubleshooting Amazon WorkDocs Administration

### ISSUE THREAD

**Issue by lkdavies** [awsdocs/amazon-workdocs-administration-guide#1]
We're looking for your real-world solutions, tips, and tricks for administering Amazon WorkDocs.

Comment below to let us know what you've learned, or submit a pull request (see [Guidelines for contributing](https://github.com/awsdocs/amazon-workdocs-administration-guide/blob/master/CONTRIBUTING.md)).

If your suggestion is likely to help others, we'll add it to the [Amazon WorkDocs Administration Guide](https://docs.aws.amazon.com/workdocs/latest/adminguide/what_is.html). 

Thanks!

**Comment by dbarlett** [comment]
https://docs.aws.amazon.com/workdocs/latest/userguide/sync_client_help.html and https://docs.aws.amazon.com/workdocs/latest/userguide/workdocs_drive_help.html should link to https://docs.aws.amazon.com/directoryservice/latest/admin-guide/ms_ad_single_sign_on.html and note that the WorkDocs [Drive] client must be configured with the directory alias, not the directory ID, to enable SSO.

**Comment by lkdavies** [comment]
Thanks for the feedback @dbarlett , we're currently confirming expected behavior with the product team.
