### ISSUE TITLE
Document describes usage of non-existant page

### ISSUE THREAD

**Issue by petercoles** [awsdocs/amazon-workdocs-administration-guide#2]
The [instructions for recovering files from the recovery bin](https://github.com/awsdocs/amazon-workdocs-administration-guide/blob/master/doc_source/manage-sites.md#recovery-bin) refer to a "Restore file page" that doesn't seem to exist (at least in Chrome or Firefox on a Mac).

Steps 1-3 work fine, but the page referred to in step 4 is nowhere to be found. It's not in the visible menus, nor is there an Actions pull down menu as on some other pages, nor is there a right click loaded context menu.

I wonder if this is referring to a feature removed in the UI update earlier this month.

**Comment by lkdavies** [comment]
Thanks for the feedback! It looks like there is now a "Recover" icon (circular arrow) that appears in the upper right when a file is selected in the Recovery Bin. Clicking the "Recover" icon brings up a pop-up called "Restore file." 

I can fix this in our docs later today, unless you would prefer to submit a pull request first?

**Comment by petercoles** [comment]
Thanks for that clarification Liz. I'd seen that icon but thought that it was for refreshing the page. Normally I'd be happy to dive in and contribute, but although it works fine for top level files, I haven't yet worked out how to recover folders or items in them, so don't feel that I've sufficiently mastered the new UI. So this time I'll be eagerly awaiting your fix!!

**Comment by lkdavies** [comment]
Thanks Peter, I've updated the [instructions for recovering files from the recovery bin](https://github.com/awsdocs/amazon-workdocs-administration-guide/blob/master/doc_source/manage-sites.md#recovery-bin). Really appreciate your help!
