### ISSUE TITLE
AWS-managed IAM policies outdated

### ISSUE THREAD

**Issue by PatMyron** [awsdocs/amazon-workdocs-administration-guide#3]
`arn:aws:iam::aws:policy/AmazonZocaloFullAccess`
`arn:aws:iam::aws:policy/AmazonZocaloReadOnlyAccess`

both reference the outdated `zocalo:*` service name instead of the new IAM action format documented here:

https://github.com/awsdocs/amazon-workdocs-administration-guide/blob/87542ffb2017ebc3fe4fb8ceed2ea378f6f670ba/doc_source/prereqs.md#L46

https://github.com/awsdocs/amazon-workdocs-administration-guide/blob/87542ffb2017ebc3fe4fb8ceed2ea378f6f670ba/doc_source/prereqs.md#L79

**Comment by lkdavies** [comment]
Thank you, we are currently investigating this with the Amazon WorkDocs service team.

**Comment by lkdavies** [comment]
Hi, 

Thank you for your feedback on our documentation. At this time, the related IAM policies do use the term zocalo, so we have updated the documentation to reflect the current state.

The Amazon WorkDocs service team has been made aware of the issue you raised. If you would like to communicate this issue to the service team also, you can post this issue on the AWS Developer Forum for Amazon WorkDocs here: https://forums.aws.amazon.com/forum.jspa?forumID=172 

I hope this helps.
