### ISSUE TITLE
Power user role?

### ISSUE THREAD

**Issue by jyjohnson** [awsdocs/amazon-workdocs-administration-guide#4]
I don't see any documentation on what this means or how this role "...can be given a special set of permissions by the Administrator".

**Comment by lkdavies** [comment]
Thanks for your feedback on our documentation. I don't see an obvious way to assign special permissions to a Power User, either. I've contacted the service team for more information about how the role works, and will update here when I have more info.

**Comment by lkdavies** [comment]
Hi,
Amazon WorkDocs administrators can assign permissions to Power users by signing in to the console and opening the Admin control panel. The available permissions are listed under the Admin Security settings. For more information, see https://docs.aws.amazon.com/workdocs/latest/adminguide/manage-sites.html 
Thanks, 
Liz
